Add CSS
kalviumcommunity/Ornate pull request #4
Opened 2023-03-06 04:36 UTC by Ranapriyanshi

2023-03-10 10:19 UTC, aditya-190 requested changes
Please make the required changes before merging the changes.

2023-03-10 10:19 UTC, aditya-190 commented on ornate_frontend/src/index.js
> +      <Route path="/SignUp" element={<SignUp />}></Route>
According to React naming convection routes are generally in `snake_case`. Please try to change them in your later PR's. To know more about, check this out -> https://www.upbeatcode.com/react/react-naming-conventions/

2023-03-10 10:19 UTC, aditya-190 commented on ornate_frontend/src/index.js
> +      <Route path="/" element={<Home />}></Route>
`Route` is an self closing tag. You can replace it with - `<Route path="/" element={<Home />} />`

2023-03-10 10:19 UTC, aditya-190 commented on ornate_frontend/src/pages/Home.js
> +        <div className="cards">
Small Code optimization can be achieved by extracting the repeated code into a new component and implementing loops to efficiently execute it as many times as required.

2023-03-13 11:59 UTC, PatelNeelMahesh approved these changes
Since, you completed all the changes you can merge pull request.

2023-03-13 12:32 UTC, merged